version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: median-postgres
    environment:
      POSTGRES_USER: median
      POSTGRES_PASSWORD: median123
      POSTGRES_DB: median_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: